# Check if build files have not been generated by checking for target/CMakeCache.txt
$buildCachePath = "target/CMakeCache.txt"

if (-Not (Test-Path $buildCachePath)) {
    cmake --preset=default
    if ($LASTEXITCODE -ne 0) {
        Write-Host "CMake configuration failed. Please check the output for errors."
        exit $LASTEXITCODE
    }

    # Check for CMakeCache.txt again to confirm successful configuration
    if (-Not (Test-Path $buildCachePath)) {
        Write-Host "CMake configuration did not create CMakeCache.txt. Please check the output for errors."
        exit 1
    }
}

cmake --build target
